---
title: "Exploratory Analysis"
author: "Adam Raikes"
date: "November 28, 2016"
output: 
  pdf_document:
    includes:
      in_header: header.tex
---
```{r setGlobal, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r comments, echo = FALSE}
#### File Description ####
# Author: Adam Raikes
# Initial Date: 11/14/2016
# Local Depends: Trial Validation.R
# Local Files: ./Data Files/Raw_Vision.csv, ./Data Files/MMSE_Vision.csv,
# ./Data Files/Detrended_Vision.csv
#
# Description: This is an exploratory analysis of the nonlinear metrics for the
# visual-motor tracking task. At present, only MMSE is computed. This file
# depends on Trial Validation.R to import the RMSE for the trials.
#
# This exploratory analysis will focus primarily on graphical representations of
# variables to assess the overall coherence of the dataset. Primary plots will be
# boxplots.
```


```{r loadLibraries}
#### Load libraries ####
# This will be accomplished by "require" to avoid unnecessary loading.
require(tidyverse)
require(ggplot2)
require(furniture)
require(cowplot)
```

```{r sourceFiles}
# Some of the functions used as well as participant and data cleaning require
# loading custom functions

# Comment out the setwd command when rendering from with Dissertation analyses.R.
setwd("../")
my_dir <- getwd()
print(my_dir)

#### Load helper functions ####
source("./R Script files/Helper functions.R")

#### Get minimal participant information ####
source("./R Script files/Participant information.R")
```

```{r descriptiveStatistics}
part.desc <- select(participants, height, weight, age, gender, hand, gamer, 
                    diagnosed.number, suspected.number, concussion.number,
                    prior.concussion)

table1(part.desc, 
       height, weight, age, gender, hand, gamer, 
        diagnosed.number, suspected.number, concussion.number,
       splitby = ~prior.concussion,
       test = TRUE,
       output_type = "markdown")
```

\newpage

\center

#Boxplots of outcomes by factor-level predictors

\newpage
\blandscape

```{r readData}
#### Read in outcomes data ####
mmse.data <- read.csv(paste(my_dir, "./Data Files/MMSE.csv", sep = ""),
                      header = TRUE, sep = ",")
mmse.detrended.data <- read.csv(paste(my_dir, "./Data Files/Detrended MMSE.csv", sep = ""),
                                header = TRUE, sep = ",")
dfa.data <- read.csv(paste(my_dir, "/Data Files/DFA.csv", sep = ""),
                     header = TRUE, sep = ",")
avp.data <- read.csv(paste(my_dir, "./Data Files/AvP.csv", sep = ""),
                     header = TRUE, sep = ",")
trial.summary <- read.csv(paste(my_dir, "./Data Files/Trial Summary.csv", sep = ""),
                          header = TRUE, sep = ",")

# Create dataframe with only complexity for MMSE and detrended MMSE
raw.complexity <- group_by(mmse.data, id) %>%
  gather(scale, value, -id, -trial, -block) %>%
  group_by(id, block, trial) %>%
  summarise(complexity = sum(value))

detrended.complexity <- group_by(mmse.detrended.data, id) %>%
  gather(scale, value, -id, -trial, -block) %>%
  group_by(id, block, trial) %>%
  summarise(detrended.complexity = sum(value))
```


```{r createJointFrame}
full.frame <- left_join(dfa.data, avp.data) %>%
  left_join(trial.summary) %>%
  left_join(raw.complexity) %>%
  left_join(detrended.complexity) %>%
  left_join(participants)
```

```{r boxplots, results = "asis", fig.height = 10, fig.width = 16}
outcomes <- c("rmse.V", "complexity",
              "detrended.complexity", "avp04", "avp48", 
              "avp812", "alpha")
titles <- c("RMSE", "Complexity", "Detrended Complexity",
            "Average 0-4 Hz Power",
            "Average 4-8 Hz Power", "Average 8-12 Hz Power",
            "DFA Alpha")

for (i in 1:length(outcomes)){
  a <- my_boxplot(group = "block", y = outcomes[i], data = full.frame)
  b <- my_boxplot(group = "prior.concussion", y = outcomes[i], data = full.frame)
  c <- my_boxplot(group = "gender", y = outcomes[i], data = full.frame)
  d <- my_boxplot(group = "gamer", y = outcomes[i], data = full.frame)
  
  grid <- plot_grid(a, b, c, d,
                    labels = c("A", "B", "C", "D"),
                    ncol = 2)
  title <- ggdraw() + draw_label(titles[i], fontface = "bold")
  
  panel_plot <- plot_grid(title, grid, ncol = 1, rel_heights = c(0.1,1))

  print(panel_plot)
  cat("\\newpage")
}
```
\elandscape

\center

# Scatterplots of outcomes and continuous participant values

\newpage
\blandscape

```{r scatterplots, results = "asis", fig.height = 12, fig.width = 16}
desc = c("age", "center.N", "diagnosed.number", "suspected.number", "concussion.number")

for (i in 1:length(outcomes)){
  cols <- c(desc, outcomes[i])
  
  scat <- my_scatterplot(cols = cols, title = titles[i], data = full.frame)
  
  print(scat)
  cat("\\newpage")
}
```

\elandscape

\center

# Individual plots

\newpage
\blandscape

```{r addOutlierFlag}
# Outcomes-only frame with outcome flags
raw.complexity <- mutate(raw.complexity, outcome = "MMSE") %>%
  rename(value = complexity)

detrended.complexity <- mutate(detrended.complexity, outcome = "Detrended MMSE") %>%
  rename(value = detrended.complexity)

dfa.data.long <- mutate(dfa.data, outcome = "DFA") %>%
  rename(value = alpha)

avp.data.long <- gather(avp.data, outcome, value, -id, -block, -trial)

individual.frame <- bind_rows(raw.complexity, detrended.complexity, 
                              dfa.data.long, avp.data.long)

individual.frame <- group_by(individual.frame, id, outcome) %>%
  mutate(outlier = ifelse(is_outlier(value), trial, as.numeric(NA)))
```

```{r individualOutcomes, fig.height = 8, fig.width = 14}
# Plot individual boxplots for outcomes
id.vec <- ungroup(individual.frame) %>% 
  distinct(id) %>% 
  select(id) %>%
  collect %>% .[["id"]]

for (i in 1:length(id.vec)){
  tmp <- filter(individual.frame, id == id.vec[i])
  
  indiv <- boxplot_outliers(y = "value", outlier = "outlier",
                                    outcome = "outcome", data = tmp)
  
  title <- ggdraw() + draw_label(paste("Participant ", id.vec[i], sep = ""),
                                 fontface = "bold")
  
  panel.plot <- plot_grid(title, indiv, ncol = 1, rel_heights = c(0.1,1))
  
  print(panel.plot)
  cat("\\newpage")
}
```

\elandscape


